"use client";

import { useEffect, useState } from "react";
import { Download, FilePenLine, Plus, RefreshCw, Upload } from "lucide-react";

type Item = { id: string; section: string; slug: string; title: string; body: string; status: "draft" | "published" | "archived"; sortOrder: number; updatedAt: string; updatedBy: string };
function tokenHeaders(token: string): Record<string, string> { return token ? { "x-admin-token": token } : {}; }
const empty = { id: "", section: "travel-guide", slug: "", title: "", body: "", status: "draft" as const, sortOrder: 100 };

export function ContentAdmin({ token, canEdit }: { token: string; canEdit: boolean }) {
  const [items, setItems] = useState<Item[]>([]);
  const [form, setForm] = useState<{ id: string; section: string; slug: string; title: string; body: string; status: "draft" | "published" | "archived"; sortOrder: number }>(empty);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function load() { setBusy(true); try { const r=await fetch("/api/admin/content",{headers:tokenHeaders(token),cache:"no-store"}); const d=await r.json(); if(!r.ok) throw new Error(d.error||`HTTP ${r.status}`); setItems(d.items||[]); } catch(e){setMessage(e instanceof Error?e.message:"Ошибка загрузки контента");} finally{setBusy(false);} }
  useEffect(()=>{void load();},[token]);
  async function save() { setBusy(true); setMessage(""); try { const r=await fetch("/api/admin/content",{method:"POST",headers:{"content-type":"application/json",...tokenHeaders(token)},body:JSON.stringify(form)}); const d=await r.json(); if(!r.ok) throw new Error(d.error||`HTTP ${r.status}`); setMessage("Материал сохранён и записан в audit trail."); setForm(empty); await load(); } catch(e){setMessage(e instanceof Error?e.message:"Ошибка сохранения");} finally{setBusy(false);} }
  async function exportBundle(){setBusy(true);setMessage("");try{const r=await fetch("/api/admin/content-export",{headers:tokenHeaders(token),cache:"no-store"});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error||`HTTP ${r.status}`)}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=(r.headers.get("content-disposition")||"").match(/filename="([^"]+)"/u)?.[1]||"okno-content.json";a.click();URL.revokeObjectURL(url);setMessage("Managed content экспортирован.");}catch(e){setMessage(e instanceof Error?e.message:"Ошибка экспорта");}finally{setBusy(false)}}
  async function importBundle(file:File|null){if(!file)return;if(file.size>1_048_576){setMessage("Файл больше 1 МБ.");return}setBusy(true);setMessage("");try{const text=await file.text();const dry=await fetch("/api/admin/content-import?dryRun=1",{method:"POST",headers:{"content-type":"application/json",...tokenHeaders(token)},body:text});const preview=await dry.json();if(!dry.ok)throw new Error(preview.error||`HTTP ${dry.status}`);const ok=window.confirm(`Импорт: ${preview.total} материалов; новых ${preview.created}; обновлений ${preview.updated}. Продолжить?`);if(!ok){setMessage("Импорт отменён после dry-run.");return}const r=await fetch("/api/admin/content-import",{method:"POST",headers:{"content-type":"application/json",...tokenHeaders(token)},body:text});const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);setMessage(`Импортировано ${d.total}: новых ${d.created}, обновлено ${d.updated}.`);await load();}catch(e){setMessage(e instanceof Error?e.message:"Ошибка импорта");}finally{setBusy(false)}}
  return <section className="border border-white/10 bg-[#14161a] p-5 sm:p-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><FilePenLine className="size-5 text-[#6f91ff]"/><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-zinc-500">Managed content</p><h2 className="text-lg font-black text-white">Корпоративные заметки</h2></div></div><div className="flex gap-2"><button onClick={()=>void exportBundle()} disabled={!canEdit||busy} className="border border-white/10 p-2 text-zinc-400 disabled:opacity-40" title="Экспорт JSON"><Download className="size-4"/></button><label className={`cursor-pointer border border-white/10 p-2 text-zinc-400 ${!canEdit||busy?"pointer-events-none opacity-40":""}`} title="Импорт JSON"><Upload className="size-4"/><input type="file" accept="application/json,.json" className="hidden" onChange={e=>{void importBundle(e.target.files?.[0]??null);e.currentTarget.value=""}}/></label><button onClick={()=>void load()} disabled={busy} className="border border-white/10 p-2 text-zinc-400"><RefreshCw className={`size-4 ${busy?"animate-spin":""}`}/></button></div></div>
    <p className="mt-2 text-sm leading-6 text-zinc-500">Публикуемые здесь материалы появляются в разделе «Перед поездкой» без пересборки приложения. Export/import использует версионированный JSON bundle и dry-run перед записью.</p>
    <div className="mt-4 grid gap-2 sm:grid-cols-2">
      <input value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))} disabled={!canEdit} placeholder="Заголовок" className="h-10 border border-white/10 bg-black/20 px-3 text-sm text-white outline-none"/>
      <input value={form.slug} onChange={e=>setForm(v=>({...v,slug:e.target.value}))} disabled={!canEdit} placeholder="slug, например visa-update" className="h-10 border border-white/10 bg-black/20 px-3 font-mono text-sm text-white outline-none"/>
      <select value={form.status} onChange={e=>setForm(v=>({...v,status:e.target.value as typeof v.status}))} disabled={!canEdit} className="h-10 border border-white/10 bg-[#101216] px-3 text-sm text-white"><option value="draft">draft</option><option value="published">published</option><option value="archived">archived</option></select>
      <input type="number" value={form.sortOrder} onChange={e=>setForm(v=>({...v,sortOrder:Number(e.target.value)||100}))} disabled={!canEdit} className="h-10 border border-white/10 bg-black/20 px-3 text-sm text-white"/>
    </div>
    <textarea value={form.body} onChange={e=>setForm(v=>({...v,body:e.target.value}))} disabled={!canEdit} placeholder="Текст корпоративной заметки" className="mt-2 min-h-28 w-full border border-white/10 bg-black/20 p-3 text-sm text-white outline-none"/>
    <div className="mt-3 flex flex-wrap items-center gap-3"><button onClick={()=>void save()} disabled={!canEdit||busy} className="inline-flex h-10 items-center gap-2 bg-[#285fff] px-4 text-xs font-black uppercase tracking-[0.1em] text-white disabled:opacity-40"><Plus className="size-4"/>{form.id?"Обновить":"Добавить"}</button>{message&&<span className="text-xs text-zinc-500">{message}</span>}</div>
    <div className="mt-5 space-y-2">{items.map(item=><button key={item.id} type="button" onClick={()=>setForm({id:item.id,section:item.section,slug:item.slug,title:item.title,body:item.body,status:item.status,sortOrder:item.sortOrder})} className="block w-full border-b border-white/6 py-3 text-left"><div className="flex items-center justify-between gap-3"><span className="font-semibold text-zinc-200">{item.title}</span><span className={item.status==="published"?"text-xs font-bold text-emerald-400":item.status==="draft"?"text-xs font-bold text-amber-400":"text-xs text-zinc-600"}>{item.status}</span></div><p className="mt-1 truncate text-xs text-zinc-600">{item.slug} · {item.updatedBy}</p></button>)}</div>
  </section>;
}
