import type { NewsItem } from "@/lib/data";

export type NewsSourceLanguage = "zh" | "en" | "ru";
export type NewsSourceFocus = "auto" | "truck" | "ev" | "economy" | "technology" | "policy" | "trade";

export type NewsWebsiteSource = {
  id: string;
  name: string;
  url: string;
  market: "Россия" | "Китай" | "Международный";
  language: NewsSourceLanguage;
  sourceType: "official" | "media";
  priority: number;
  focus: NewsSourceFocus[];
  maxCandidates?: number;
  enabledByDefault: boolean;
  note: string;
  hostAliases?: string[];
};

/**
 * Source policy for Window to China v1.7/v1.7.1.
 *
 * Priority is editorial for duplicate resolution, not a general media-quality score:
 * primary/official data beats secondary reporting; specialist automotive/truck originals
 * beat broad aggregators; Telegram stays useful for speed but loses duplicate conflicts
 * to an identifiable original or official publication.
 */
export const newsWebsiteSources: readonly NewsWebsiteSource[] = Object.freeze([
  {
    id: "shaanxi-auto",
    name: "Shaanxi Automobile",
    url: "https://www.sxqc.com/",
    market: "Китай",
    language: "zh",
    sourceType: "official",
    priority: 100,
    focus: ["auto", "truck"],
    maxCandidates: 3,
    enabledByDefault: true,
    note: "Официальные новости SHACMAN / Shaanxi Automobile, включая тяжёлые грузовики и экспорт.",
  },
  {
    id: "caam",
    name: "CAAM",
    url: "https://www.caam.org.cn/",
    market: "Китай",
    language: "zh",
    sourceType: "official",
    priority: 100,
    focus: ["auto", "truck", "ev", "trade", "policy"],
    maxCandidates: 3,
    enabledByDefault: true,
    note: "Ассоциация автопроизводителей Китая: продажи, производство, экспорт, коммерческий транспорт.",
  },
  {
    id: "miit-auto",
    name: "MIIT China · Automotive Industry",
    url: "https://www.miit.gov.cn/jgsj/zbys/qcgy/",
    market: "Китай",
    language: "zh",
    sourceType: "official",
    priority: 100,
    focus: ["auto", "truck", "ev", "technology", "policy"],
    maxCandidates: 3,
    enabledByDefault: true,
    note: "Министерство промышленности КНР: автомобильная политика, стандарты, продуктовые допуски, NEV и smart vehicles.",
  },
  {
    id: "mofcom-news",
    name: "MOFCOM China",
    url: "https://english.mofcom.gov.cn/News/index.html",
    market: "Китай",
    language: "en",
    sourceType: "official",
    priority: 100,
    focus: ["trade", "economy", "policy"],
    maxCandidates: 2,
    enabledByDefault: true,
    note: "Министерство коммерции КНР: экспорт, импорт, инвестиции, международная торговля и меры регулирования.",
  },
  {
    id: "nbs-china",
    name: "National Bureau of Statistics of China",
    url: "https://www.stats.gov.cn/english/PressRelease/",
    market: "Китай",
    language: "en",
    sourceType: "official",
    priority: 100,
    focus: ["economy", "policy"],
    maxCandidates: 2,
    enabledByDefault: true,
    note: "Официальная макростатистика Китая: промышленность, производство, инвестиции и внешняя торговля.",
  },
  {
    id: "cada",
    name: "China Automobile Dealers Association",
    url: "https://www.cada.cn/",
    market: "Китай",
    language: "zh",
    sourceType: "official",
    priority: 98,
    focus: ["auto", "truck", "ev", "policy"],
    maxCandidates: 3,
    enabledByDefault: true,
    note: "Рынок новых и подержанных автомобилей, дилерские запасы и отраслевые отчёты.",
    hostAliases: ["data.cada.cn"],
  },
  {
    id: "chinatruck",
    name: "卡车网 · China Truck",
    url: "https://www.chinatruck.org/news/",
    market: "Китай",
    language: "zh",
    sourceType: "media",
    priority: 93,
    focus: ["truck", "ev", "technology", "trade"],
    maxCandidates: 4,
    enabledByDefault: true,
    note: "Специализированная лента по тяжёлым и лёгким грузовикам, тягачам, силовым агрегатам и коммерческому транспорту Китая.",
    hostAliases: ["m.chinatruck.org"],
  },
  {
    id: "360che-truck",
    name: "卡车之家 · 360che",
    url: "https://www.360che.com/news/",
    market: "Китай",
    language: "zh",
    sourceType: "media",
    priority: 92,
    focus: ["truck", "ev", "technology"],
    maxCandidates: 4,
    enabledByDefault: true,
    note: "Рынок HCV/MCV/LCV Китая, бренды, страховые регистрации,新能源重卡, батареи и продуктовые объявления.",
  },
  {
    id: "people-auto",
    name: "人民网汽车",
    url: "https://auto.people.com.cn/",
    market: "Китай",
    language: "zh",
    sourceType: "official",
    priority: 94,
    focus: ["auto", "ev", "policy"],
    maxCandidates: 2,
    enabledByDefault: true,
    note: "Автомобильная лента People's Daily Online.",
  },
  {
    id: "xinhua-auto",
    name: "新华网汽车",
    url: "https://www.xinhuanet.com/auto/",
    market: "Китай",
    language: "zh",
    sourceType: "official",
    priority: 94,
    focus: ["auto", "ev", "policy"],
    maxCandidates: 2,
    enabledByDefault: true,
    note: "Автомобильная лента Xinhua; при дубле сохраняется первичная публикация.",
    hostAliases: ["www.news.cn", "auto.news.cn"],
  },
  {
    id: "cctv-auto",
    name: "央视网汽车",
    url: "https://auto.cctv.com/",
    market: "Китай",
    language: "zh",
    sourceType: "official",
    priority: 92,
    focus: ["auto", "ev", "policy"],
    maxCandidates: 2,
    enabledByDefault: true,
    note: "Автомобильная лента CCTV.",
  },
  {
    id: "gasgoo",
    name: "Gasgoo",
    url: "https://autonews.gasgoo.com/",
    market: "Китай",
    language: "en",
    sourceType: "media",
    priority: 91,
    focus: ["auto", "truck", "ev", "technology", "trade"],
    maxCandidates: 3,
    enabledByDefault: true,
    note: "Специализированные новости китайского автопрома, Tier-1/Tier-2, батареи и рынок.",
    hostAliases: ["www.gasgoo.com", "gasgoo.com"],
  },
  {
    id: "cnevpost",
    name: "CnEVPost",
    url: "https://cnevpost.com/industry/",
    market: "Китай",
    language: "en",
    sourceType: "media",
    priority: 90,
    focus: ["ev", "auto", "truck", "trade"],
    maxCandidates: 3,
    enabledByDefault: true,
    note: "Китайский NEV/EV рынок, продажи, экспорт, батареи и регулирование.",
  },
  {
    id: "yicai-auto",
    name: "Yicai Global",
    url: "https://www.yicaiglobal.com/auto",
    market: "Китай",
    language: "en",
    sourceType: "media",
    priority: 85,
    focus: ["auto", "truck", "economy", "trade", "policy"],
    maxCandidates: 2,
    enabledByDefault: true,
    note: "Китайский бизнес, автопром, локализация, экспорт и инвестиции.",
  },
  {
    id: "china-briefing",
    name: "China Briefing",
    url: "https://www.china-briefing.com/news/",
    market: "Китай",
    language: "en",
    sourceType: "media",
    priority: 83,
    focus: ["economy", "policy", "trade"],
    maxCandidates: 2,
    enabledByDefault: true,
    note: "Регуляторика, экономика, инвестиции и внешняя торговля Китая.",
  },
  {
    id: "autohome",
    name: "汽车之家",
    url: "https://www.autohome.com.cn/",
    market: "Китай",
    language: "zh",
    sourceType: "media",
    priority: 80,
    focus: ["auto", "ev"],
    maxCandidates: 2,
    enabledByDefault: true,
    note: "Широкая автомобильная лента Китая.",
  },
  {
    id: "yiche",
    name: "易车",
    url: "https://www.yiche.com/",
    market: "Китай",
    language: "zh",
    sourceType: "media",
    priority: 79,
    focus: ["auto", "ev"],
    maxCandidates: 2,
    enabledByDefault: true,
    note: "Китайский автомобильный портал.",
  },
  {
    id: "pcauto",
    name: "太平洋汽车",
    url: "https://www.pcauto.com.cn/",
    market: "Китай",
    language: "zh",
    sourceType: "media",
    priority: 78,
    focus: ["auto", "ev"],
    maxCandidates: 2,
    enabledByDefault: true,
    note: "Китайский автомобильный портал PCauto.",
  },
  {
    id: "36kr-en",
    name: "36Kr Global",
    url: "https://eu.36kr.com/en/",
    market: "Китай",
    language: "en",
    sourceType: "media",
    priority: 77,
    focus: ["technology", "auto", "ev", "economy"],
    maxCandidates: 2,
    enabledByDefault: true,
    note: "Технологии, AI, роботизация, стартапы и smart mobility Китая.",
  },
  {
    id: "carnewschina",
    name: "CarNewsChina",
    url: "https://carnewschina.com/",
    market: "Китай",
    language: "en",
    sourceType: "media",
    priority: 74,
    focus: ["auto", "ev"],
    maxCandidates: 2,
    enabledByDefault: true,
    note: "Быстрая лента китайских автомобилей и EV; вторичная по отношению к официальным источникам.",
  },
  {
    id: "evolute-official",
    name: "EVOLUTE",
    url: "https://www.evolute.ru/about/news/announcements",
    market: "Россия",
    language: "ru",
    sourceType: "official",
    priority: 100,
    focus: ["auto", "ev", "technology", "trade"],
    maxCandidates: 5,
    enabledByDefault: true,
    note: "Официальные пресс-релизы EVOLUTE: модельный ряд, производство в России, продажи, локализация и сервис.",
    hostAliases: ["evolute.ru"],
  },
  {
    id: "voyah-official",
    name: "VOYAH Россия",
    url: "https://voyah.ru/news/anons",
    market: "Россия",
    language: "ru",
    sourceType: "official",
    priority: 100,
    focus: ["auto", "ev", "technology", "trade"],
    maxCandidates: 5,
    enabledByDefault: true,
    note: "Официальные новости VOYAH в России: модельный ряд, производство, продажи, локализация и дилерская сеть.",
    hostAliases: ["voyah.ru"],
  },
  {
    id: "ural-official",
    name: "Автозавод УРАЛ",
    url: "https://uralaz.ru/media/news/",
    market: "Россия",
    language: "ru",
    sourceType: "official",
    priority: 100,
    focus: ["truck", "technology", "trade"],
    maxCandidates: 3,
    enabledByDefault: true,
    note: "Официальные новости российского производителя тяжёлых грузовиков и специальной техники УРАЛ.",
  },
  {
    id: "gruzovoy-ru",
    name: "Грузовой.RU",
    url: "https://gruzovoy.ru/news",
    market: "Россия",
    language: "ru",
    sourceType: "media",
    priority: 88,
    focus: ["truck", "auto", "technology", "trade"],
    maxCandidates: 4,
    enabledByDefault: true,
    note: "Российский рынок коммерческого транспорта: модели, продажи, китайские и российские грузовые бренды.",
  },
  {
    id: "gruzovikpress",
    name: "Грузовик Пресс",
    url: "https://www.gruzovikpress.ru/",
    market: "Россия",
    language: "ru",
    sourceType: "media",
    priority: 86,
    focus: ["truck", "technology", "trade"],
    maxCandidates: 3,
    enabledByDefault: true,
    note: "Грузовики, тягачи, спецтехника, компоненты, эксплуатация, логистика и отраслевые выставки России.",
    hostAliases: ["gruzovikpress.ru"],
  },
  {
    id: "reis-trucks",
    name: "Рейс · Грузовики",
    url: "https://reis.zr.ru/articles/avtomobili/gruzoviki/",
    market: "Россия",
    language: "ru",
    sourceType: "media",
    priority: 84,
    focus: ["truck", "technology", "trade"],
    maxCandidates: 3,
    enabledByDefault: true,
    note: "Новости и практическая аналитика грузового транспорта, тягачей и российского коммерческого рынка.",
  },
  {
    id: "china-daily-motoring",
    name: "China Daily Motoring",
    url: "https://global.chinadaily.com.cn/business/5c2336fea310d91214051089",
    market: "Китай",
    language: "en",
    sourceType: "media",
    priority: 68,
    focus: ["auto", "ev", "economy"],
    maxCandidates: 2,
    enabledByDefault: false,
    note: "Резервный источник: часть материалов повторяет агентские/официальные публикации.",
  },
  {
    id: "caixin-global",
    name: "Caixin Global",
    url: "https://www.caixinglobal.com/auto/",
    market: "Китай",
    language: "en",
    sourceType: "media",
    priority: 87,
    focus: ["auto", "economy", "policy", "trade"],
    maxCandidates: 2,
    enabledByDefault: false,
    note: "Глубокая бизнес-аналитика; по умолчанию выключено из-за возможного paywall/bot protection.",
  },
  {
    id: "gacc-statistics",
    name: "China Customs (GACC)",
    url: "https://english.customs.gov.cn/Statistics/Statistics",
    market: "Китай",
    language: "en",
    sourceType: "official",
    priority: 100,
    focus: ["trade", "economy"],
    maxCandidates: 1,
    enabledByDefault: false,
    note: "Официальная внешнеторговая статистика; data-source candidate, а не оперативная новостная лента.",
  },
]);

export const activeNewsWebsiteSources = newsWebsiteSources.filter((source) => source.enabledByDefault);

const sourcePriorities = new Map(newsWebsiteSources.map((source) => [source.name, source.priority]));

export function priorityForNewsItem(item: Pick<NewsItem, "source" | "sourceType">) {
  const configured = sourcePriorities.get(item.source);
  if (configured != null) return configured;
  if (item.source === "АВТОСТАТ") return 90;
  if (item.sourceType === "official") return 95;
  if (item.sourceType === "media") return 72;
  return 55;
}

export function validateNewsSourceCatalog() {
  const ids = new Set<string>();
  const urls = new Set<string>();
  const duplicates: string[] = [];
  for (const source of newsWebsiteSources) {
    if (ids.has(source.id)) duplicates.push(`id:${source.id}`);
    ids.add(source.id);
    const normalized = new URL(source.url).toString();
    if (urls.has(normalized)) duplicates.push(`url:${normalized}`);
    urls.add(normalized);
  }
  return { valid: duplicates.length === 0, duplicates, total: newsWebsiteSources.length, active: activeNewsWebsiteSources.length };
}
